version: "3"
services:
  app:
    build: .
    container_name: r3f
    labels:
      - "traefik.http.routers.r3f.rule=Host(`r3f.mcxue.cn`)"
      - "traefik.http.routers.r3f.tls=true"
      - "traefik.http.routers.r3f.tls.certresolver=le"

networks:
  default:
    external:
      name: traefik_default
